ourGitLabGroup = "https://gitlab.com/UniGrammar/"
ourGitHubOrg = "https://github.com/UniGrammar/"
ourProjectLink = ourGitHubOrg + "UniGrammar.py"
grammarsRepoLink = ourGitHubOrg + "grammars"
runtimeModuleName = "UniGrammarRuntime"
runtimeParserBackendModuleName = "IParsingBackend"
runtimeWrapperInterfaceModuleName = runtimeWrapperInterfaceName = "IWrapper"
runtimeParserResultBaseName = "IParseResult"
mainParserVarName = "__MAIN_PARSER__"
mainProductionName = "__MAIN_PRODUCTION__"
